### ISSUE TITLE
Items learned on linked server show as unlearned on dif armor toon

### ISSUE THREAD

**Issue by Barleduq** [Caerdon/CaerdonWardrobe#35] opened 2022-12-03 08:59 UTC
I just boosted my Clothie (mage) to L60. I had stored cloth items I'd gotten from Shadowlands, and pulled them out of storage and learned them.  There were some duplicate appearances, which I sent to my AH toon.  AH toon is a leather wearer (L53 rogue), and on the linked server.  In the bags of the AH toon, the item shows as not learned. 

FWIW, I have both addons installed because at least one of the transmog/appearance addons I have requires it. I honestly don't recall, at this point, which one I installed first, or which other addons require each. And I don't currently have the mental energy to figure it out, tho I cna put it on my list for when I'm finally going through my addons to call out the errors I'm seeing. 

Concisely: Appearances learned on L60 Mage on Eitrigg show as unlearned in bags of L53 Rogue on Shu'halo. 

Is this working as intended?  If so, could I request a feature, that this works?  I've actually gotten bitten by this before, buying something on the AH that shows as unlearned and sending it over, only to find that I already know the appearance.  I don't have a max level of every armor type on Shu'halo. ANd if I did, things would still show as unlearned on the Eitrigg toons. 

Thank you!
-Barleduq

**Comment by Caerdon** [comment] 2022-12-03 15:50
I'm assuming you're referring to CanIMogIt regarding having both addons installed.  It's fine to have both addons installed as they shouldn't interfere with each other.  My goal is to ensure that Caerdon accurately reflects the state of an item no matter which toon is holding on to it, so that's not working as intended.  That said, it's hard to say specifically what's going on without knowing which items you're specifically talking about. 

I've definitely seen the behavior in the past, and there was a point where Blizzard didn't give enough info for me to accurately identify it until it was handed over to the proper toon (in certain cases).  It seems much improved in this regard, but there are always edge cases, and I have to know the exact items if so.

I'll try this specific scenario (grab something for my clothie, learn it, and pass a duplicate to my leather wearer and see if I can reproduce).  Otherwise, I'll need more info here to help!

**Comment by Caerdon** [comment] 2022-12-03 15:53
Also, in the latest version of Caerdon Wardrobe, if you enable Debug mode in Caerdon's settings, and you have CanIMogIt installed, I'll do some comparisons between what CanIMogIt thinks and what Caerdon thinks about an item and report some info in your chat window if I find differences (when you open your bags or do an auction search for now).

If you have the item with your leather wearer still, you could turn that on, open your bags, and capture what gets reported for me.

**Comment by Barleduq** [comment] 2022-12-03 17:35
Yes, I was referring to CanIMogIt, sorry for not being clear. 
I've already put the pieces that gave me confusion today onto the AH. Right this moment, my game is frozen and I'm having problems convincing it to come back. I'm also about to be in raid, so I may end up with a few more hours until I can poke further at this.  IIRC it was pieces from the Shimmering Bough set. 

I did try turning each one off, and both of hte addons claim it isn't learned.  This does make me think it's something on Blizz's end, but I don't really have a way to complain to them. :D 

Will work on this, thanks!
-Barleduq

**Comment by Caerdon** [comment] 2022-12-03 17:40
Ok thanks - when you have a chance to get the specific item, please let me know!  I tried the basic scenario you mentioned, and things are working fine, so there's something specific going on there.  Also, can you confirm if you send it back to your cloth wearer again that it still shows as learned?

**Comment by Barleduq** [comment] 2022-12-06 13:39
Just as I finished cropping, and opened this to send, I recalled that you wanted the debug information.  I'm sending this along now, because I feel like 3 days is a bit long.  I'll try to turn the debug on and take pics again before another 3 days. 

The files are titled by the item (more or less the name) and the character it's on.  CEM is the leather-wearing AH toon.  Rhythm is the clothie.  I also noticed some weirdness with some plate mail, so I'm including pics of that too - on CEM and Loco.  I had 2 pieces for both. 

I think I lost a picture.   I had looked at one of the plate pieces on CEM, and it was fine. I turned away from the screen to talk to someone RL, turned back, and it said learned in one place and not learned in another.  The pics I took after that I included the "Screenshot..." portion in the name, instead of overwriting it, to get a finer timestamp.  So there are 8 pics: 2 cloth pieces, on CEM and Rhythm, and 2 plate pieces, on CEM and Loco. 

![MawswornGirdle-OnCEM-pic1-Screenshot_2022-12-05_17-07-46](https://user-images.githubusercontent.com/20568287/205927166-e7237133-fff1-432a-bb4d-102cbd6b9cc8.png)
![MawswornGuardBreast-onCEM-Screenshot_2022-12-05_17-14-16](https://user-images.githubusercontent.com/20568287/205927196-734b5
![ShimmerboughGloves-Rhythm-Screenshot_2022-12-05_17-
![ShimmerboughWaist-Rhythm-Screenshot_2022-12-05_17-17-21](https://user-images.githubusercontent.com/20568287/205927304-281613eb-d03b-448c-943d-68a5e8e1f2a2.png)

![ShimmerboughtWaistCEM20221205](https://user-images.githubusercontent.com/20568287/205927279-4f8c959f-99b7-4cbf-9ac8-9f63682ba11f.png)
18-01](https://user-images.githubusercontent.com/20568287/205927266-c8b72265-9027-4ac5-951e-58b321ec8b1a.png)
634-2fb8-47f4-9304-9210f79730ed.png)
![MawswornGuardBreast-onLoco-20221205](https://user
![ShimmerboughGlovesCEM-20221205](https://user-images.githubusercontent.com/20568287/205927246-c6637754-3691-4b93-9f91-c9b763d4cb66.png)
-im
![MawswornGuardGirdle-onLoco-20221205](https://user-images.githubusercontent.com/20568287/205927229-19bd8279-ef29-448b-b62d-7ad30c54a8f1.png)
ages.githubusercontent.com/20568287/205927218-985021d0-70b8-40fb-8b27-123868b333af.png)

**Comment by Barleduq** [comment] 2022-12-06 21:24
Ok, even hours later, not all of the pics are showing.  How do you want to do this?  My new pictures have both CaerdonWardrobe and CanIMogIt debug on, and if you want at least some of the chat output, I won't be able to crop it as much.

**Comment by Caerdon** [comment] 2022-12-08 07:59
I'm okay with uncropped pics if it will help you show what you need.  However, a few things I find interesting here.

1) For the items you're seeing issues with, it will say "You've collected this appearance, but not from this item" or "You haven't collected this appearance" depending on the toon holding it.  That message comes directly from WoW as Caerdon doesn't currently add anything to the tooltips (unless you have debug turned on).  I made a few changes that made Caerdon more accurate than this tooltip at times, but it's also possible this is the data Caerdon is getting back from WoW in which case it would explain the problem (and would likely be difficult to fix at this time as I don't plan to add a database to track across toons and introduce some of the negative performance impacts I've seen from CIMI as a result).

2) I was surprised to see the W icon on the gear as I'd generally expect that to never show up on gear.  I'm trying to figure out what would get you in that state as it's possible that icon is overriding what you may otherwise see.

**Comment by Barleduq** [comment] 2022-12-08 15:19
Ok, rather than have things not show up here, I put a post on imgur with all 8 pics:  https://imgur.com/a/xiG0dmq

I hope the pics are clear enough. 

Some of the pics have a picture of the item next to the main tooltip.  This is from another addon - I think it's Appearances.  I have various addons enabled and disabled at the moment, on various toons, due to issues with the new expac that I haven't had the mental energy to track down and report, which is why it shows inconsistently. If you'd like that in all of them, I can go through and make sure it's turned on and retake. 

Thanks for looking at this.

**Comment by Barleduq** [comment] 2022-12-08 23:15
This might want it's own thread, but I'm not sure. 
I still have debug mode on.
On a different toon than I've mentioned before, I have the guild bank open, and I've gotten multiple messages:
Caerdon: MISSING HANDLER FOR GetGuildBankItem

It seems that every time I pick up an item in my bag, I get 2-3 messages, with another 2-3 coming after, sometimes as I'm moving it across my screen, sometimes after I've put clicked into the bank.  It's not happening just with the guild bank pane open, but does happen as soon as I click to drag an item, even just in another bag without passing over the guild bank pane.

**Comment by Caerdon** [comment] 2022-12-09 07:07
I made some changes in 3.3.8 that may improve things a bit.  I need to address the GetGuildBankItem error still but will do that shortly in the next release.

**Comment by Caerdon** [comment] 2024-05-11 00:09
I've made quite a few changes in how items are processed since this ticket was last engaged.  I'll close this for now, but if anyone runs into something that doesn't seem like it's working like it should, please open a new ticket with helpful details like this!

**Closed as completed by Caerdon** 2024-05-11 00:09 UTC
